# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.jwt-library' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJWT'
  # Pods for J.jwt-library

  target 'J.jwt-libraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.jwt-libraryUITests' do
    # Pods for testing
  end

end
